project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!cv/"
  resources:
    - CNAME
    - images/academicons-1.9.4/
    - cv/*.pdf

website:
  title: "Gidon Frischkorn"
  description: "Psychological Methods - Psychometrics - Cognitive Psychology"
  favicon: images/favicon.png
  site-url: https://www.gfrischkorn.org
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/GidonFrischkorn
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/gidon-frischkorn-4913431b1/
        aria-label: LinkedIn
  page-footer:
    center: "© 2026 Gidon Frischkorn"
  back-to-top-navigation: false

format:
  html:
    theme:
      light: [cosmo, theme-light.scss, custom.scss]
      dark:  [cosmo, theme-dark.scss, custom.scss]
    canonical-url: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="/images/academicons-1.9.4/css/academicons.min.css">
    toc: false
    link-external-icon: false
    link-external-newwindow: true

execute:
  freeze: auto
