/*== ENGINE:BEGIN ==*/
/* Facelet cube engine. Pure: no DOM, no storage, no globals beyond CUBE, so it
   can be extracted and tested headlessly (see local/engine_test.mjs).

   Ported from local/verify_algs.py. The permutation tables below were GENERATED
   by that module (`python3 local/verify_algs.py --json`) rather than written by
   hand, so they inherit its group-theoretic verification instead of needing
   their own.

   Layout: 54 stickers — U 0-8, R 9-17, F 18-26, D 27-35, L 36-44, B 45-53 —
   each face row-major in the conventions documented in verify_algs.py.
   Values are the sticker's home face: 0=U 1=R 2=F 3=D 4=L 5=B.

   Everything downstream compares cubes through `orient()`, which re-expresses a
   state in the frame its own centres define. That is what makes whole-cube
   rotations invisible and slice moves safe: a cube is "solved" if it looks
   solved to someone holding it, not if it matches a fixed colour table. */
const CUBE = (function(){
  const N = 54;
  const SOLVED = new Uint8Array(N);
  for(let i=0;i<N;i++) SOLVED[i] = (i/9)|0;
  const LETTER = ["Y","R","G","W","O","B"];
  const CENTRE = [4, 13, 22, 31, 40, 49];          // U R F D L B

  const PERM = {
    U:  [6,3,0,7,4,1,8,5,2,45,46,47,12,13,14,15,16,17,9,10,11,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,18,19,20,39,40,41,42,43,44,36,37,38,48,49,50,51,52,53],
    D:  [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,24,25,26,18,19,20,21,22,23,42,43,44,33,30,27,34,31,28,35,32,29,36,37,38,39,40,41,51,52,53,45,46,47,48,49,50,15,16,17],
    R:  [0,1,20,3,4,23,6,7,26,15,12,9,16,13,10,17,14,11,18,19,29,21,22,32,24,25,35,27,28,51,30,31,48,33,34,45,36,37,38,39,40,41,42,43,44,8,46,47,5,49,50,2,52,53],
    L:  [53,1,2,50,4,5,47,7,8,9,10,11,12,13,14,15,16,17,0,19,20,3,22,23,6,25,26,18,28,29,21,31,32,24,34,35,42,39,36,43,40,37,44,41,38,45,46,33,48,49,30,51,52,27],
    F:  [0,1,2,3,4,5,44,41,38,6,10,11,7,13,14,8,16,17,24,21,18,25,22,19,26,23,20,15,12,9,30,31,32,33,34,35,36,37,27,39,40,28,42,43,29,45,46,47,48,49,50,51,52,53],
    B:  [11,14,17,3,4,5,6,7,8,9,10,35,12,13,34,15,16,33,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,36,39,42,2,37,38,1,40,41,0,43,44,51,48,45,52,49,46,53,50,47],
    M:  [0,52,2,3,49,5,6,46,8,9,10,11,12,13,14,15,16,17,18,1,20,21,4,23,24,7,26,27,19,29,30,22,32,33,25,35,36,37,38,39,40,41,42,43,44,45,34,47,48,31,50,51,28,53],
    E:  [0,1,2,3,4,5,6,7,8,9,10,11,21,22,23,15,16,17,18,19,20,39,40,41,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,48,49,50,42,43,44,45,46,47,12,13,14,51,52,53],
    S:  [0,1,2,43,40,37,6,7,8,9,3,11,12,4,14,15,5,17,18,19,20,21,22,23,24,25,26,27,28,29,16,13,10,33,34,35,36,30,38,39,31,41,42,32,44,45,46,47,48,49,50,51,52,53],
    r:  [0,19,20,3,22,23,6,25,26,15,12,9,16,13,10,17,14,11,18,28,29,21,31,32,24,34,35,27,52,51,30,49,48,33,46,45,36,37,38,39,40,41,42,43,44,8,7,47,5,4,50,2,1,53],
    l:  [53,52,2,50,49,5,47,46,8,9,10,11,12,13,14,15,16,17,0,1,20,3,4,23,6,7,26,18,19,29,21,22,32,24,25,35,42,39,36,43,40,37,44,41,38,45,34,33,48,31,30,51,28,27],
    u:  [6,3,0,7,4,1,8,5,2,45,46,47,48,49,50,15,16,17,9,10,11,12,13,14,24,25,26,27,28,29,30,31,32,33,34,35,18,19,20,21,22,23,42,43,44,36,37,38,39,40,41,51,52,53],
    d:  [0,1,2,3,4,5,6,7,8,9,10,11,21,22,23,24,25,26,18,19,20,39,40,41,42,43,44,33,30,27,34,31,28,35,32,29,36,37,38,48,49,50,51,52,53,45,46,47,12,13,14,15,16,17],
    f:  [0,1,2,43,40,37,44,41,38,6,3,11,7,4,14,8,5,17,24,21,18,25,22,19,26,23,20,15,12,9,16,13,10,33,34,35,36,30,27,39,31,28,42,32,29,45,46,47,48,49,50,51,52,53],
    b:  [11,14,17,10,13,16,6,7,8,9,32,35,12,31,34,15,30,33,18,19,20,21,22,23,24,25,26,27,28,29,37,40,43,36,39,42,2,5,38,1,4,41,0,3,44,51,48,45,52,49,46,53,50,47],
    x:  [18,19,20,21,22,23,24,25,26,15,12,9,16,13,10,17,14,11,27,28,29,30,31,32,33,34,35,53,52,51,50,49,48,47,46,45,38,41,44,37,40,43,36,39,42,8,7,6,5,4,3,2,1,0],
    y:  [6,3,0,7,4,1,8,5,2,45,46,47,48,49,50,51,52,53,9,10,11,12,13,14,15,16,17,29,32,35,28,31,34,27,30,33,18,19,20,21,22,23,24,25,26,36,37,38,39,40,41,42,43,44],
    z:  [42,39,36,43,40,37,44,41,38,6,3,0,7,4,1,8,5,2,24,21,18,25,22,19,26,23,20,15,12,9,16,13,10,17,14,11,33,30,27,34,31,28,35,32,29,47,50,53,46,49,52,45,48,51]
  };

  /* next[i] = cur[p[i]] */
  function applyPerm(a, p){
    const out = new Uint8Array(N);
    for(let i=0;i<N;i++) out[i] = a[p[i]];
    return out;
  }
  /* apply p, then q */
  function composePerm(p, q){
    const out = new Array(N);
    for(let i=0;i<N;i++) out[i] = p[q[i]];
    return out;
  }
  function invertPerm(p){
    const out = new Array(N);
    for(let i=0;i<N;i++) out[p[i]] = i;
    return out;
  }
  const IDENT = Array.from({length:N}, (_,i)=>i);
  function powPerm(p, n){
    let out = IDENT;
    for(let i=0;i<n;i++) out = composePerm(out, p);
    return out;
  }

  /* ---- the 24 orientations, generated by composing x and y ---- */
  const ROT24 = (function(){
    const seen = new Map([[IDENT.join(","), IDENT]]);
    const queue = [IDENT];
    while(queue.length){
      const g = queue.shift();
      for(const m of ["x","y"]){
        const h = composePerm(g, PERM[m]);
        const k = h.join(",");
        if(!seen.has(k)){ seen.set(k, h); queue.push(h); }
      }
    }
    return [...seen.values()];
  })();
  /* centre signature of a rotated solved cube -> the inverse rotation */
  const BY_SIG = (function(){
    const m = new Map();
    for(const g of ROT24){
      const rotated = applyPerm(SOLVED, g);
      const sig = CENTRE.map(i=>rotated[i]).join("");
      if(!m.has(sig)) m.set(sig, invertPerm(g));
    }
    return m;
  })();

  /* Re-express a state in the frame its own centres define. */
  function orient(raw){
    const sig = CENTRE.map(i=>raw[i]).join("");
    const inv = BY_SIG.get(sig);
    return inv ? applyPerm(raw, inv) : raw;
  }

  /* ---- notation ----
     Strict and anchored: the old regex scanned past anything it did not
     recognise, so `Rw U R'` silently became `R U R'` — a learner's correct wide
     move executed as a different algorithm and marked wrong with no
     explanation. This never throws; it reports where it failed. */
  const FACES6 = "UDRLFB", SLICES = "MES", WIDES = "rlufdb", ROTS = "xyz";
  const WIDE_OF = {U:"u",D:"d",R:"r",L:"l",F:"f",B:"b"};
  const SEP = " \t\n\r·,";

  function parseMoves(text){
    const moves = [];
    const s = String(text == null ? "" : text);
    let i = 0;
    while(i < s.length){
      if(SEP.indexOf(s[i]) >= 0){ i++; continue; }
      const start = i;
      let base = s[i];
      if(FACES6.indexOf(base) >= 0){
        i++;
        if(s[i] === "w" || s[i] === "W"){ base = WIDE_OF[base]; i++; }
      } else if(SLICES.indexOf(base) >= 0 || WIDES.indexOf(base) >= 0 || ROTS.indexOf(base) >= 0){
        i++;
        if(s[i] === "w" || s[i] === "W")
          return { ok:false, at:i, token:s.slice(start, i+1),
                   why:"only face turns take a w (Rw); " + base + " is already a slice or rotation" };
      } else {
        return { ok:false, at:start, token:base,
                 why:"not a move — expected one of U D R L F B M E S x y z, or a wide turn like Rw" };
      }
      let q = 1;
      if(s[i] === "2"){ q = 2; i++; if(s[i] === "'"){ q = 2; i++; } }
      else if(s[i] === "'"){ q = 3; i++; }
      else if(s[i] === "3"){ q = 3; i++; }
      if(s[i] && SEP.indexOf(s[i]) < 0 && !PERM[s[i]] && FACES6.indexOf(s[i]) < 0)
        return { ok:false, at:i, token:s.slice(start, i+1),
                 why:"unexpected '" + s[i] + "' after " + base };
      moves.push([base, q]);
    }
    if(!moves.length) return { ok:false, at:0, token:"", why:"no moves given" };
    return { ok:true, moves:moves };
  }

  function applyMoves(raw, moves){
    let out = raw;
    for(const [base, q] of moves) out = applyPerm(out, powPerm(PERM[base], q));
    return out;
  }
  function invertMoves(moves){
    return moves.slice().reverse().map(([b,q]) => [b, (4-q)%4]).filter(m => m[1] !== 0);
  }
  function fmtMoves(moves){
    return moves.map(([b,q]) => b + (q===2 ? "2" : q===3 ? "'" : "")).join(" ");
  }

  /* ---- facelet index lists, matching verify_algs.py's conventions ---- */
  const OLL_TOP = [47,46,45], OLL_BOT = [18,19,20];
  const OLL_L = [36,37,38], OLL_R = [11,10,9];
  const PLL_RING = [47,46,45, 11,10,9, 20,19,18, 38,37,36];
  const CROSS = [[28,3],[30,3],[32,3],[34,3],[25,2],[16,1],[52,5],[43,4]];
  const SLOTS = {
    FR:[[29,3],[26,2],[15,1],[23,2],[12,1]],
    FL:[[27,3],[24,2],[44,4],[21,2],[41,4]],
    BL:[[33,3],[42,4],[53,5],[39,4],[50,5]],
    BR:[[35,3],[17,1],[51,5],[14,1],[48,5]]
  };
  const LL_CORNERS = { UBL:[0,47,36], UBR:[2,45,11], UFR:[8,9,20], UFL:[6,18,38] };
  const LL_EDGES   = { UB:[1,46], UR:[5,10], UF:[7,19], UL:[3,37] };
  const HOME = { "0,4,5":"UBL", "0,1,5":"UBR", "0,1,2":"UFR", "0,2,4":"UFL",
                 "0,5":"UB", "0,1":"UR", "0,2":"UF", "0,4":"UL" };
  const GRID = { UBL:0, UB:1, UBR:2, UL:3, UR:5, UFL:6, UF:7, UFR:8 };

  function Cube(raw){
    let _o = null, _k = null;
    const api = {
      raw: raw,                                  // RENDERING ONLY
      get o(){ return _o || (_o = orient(raw)); },
      get key(){ return _k || (_k = Array.from(api.o).join("")); },
      /* Returns null on a parse error so callers can report it. An empty or
         separator-only string is the identity, not an error — parseMoves
         rejects it because blank *user input* is a mistake, but applying no
         moves is perfectly well defined. */
      apply(alg){
        if(typeof alg === "string" && !alg.trim()) return api;
        const p = typeof alg === "string" ? parseMoves(alg) : { ok:true, moves:alg };
        return p.ok ? Cube(applyMoves(raw, p.moves)) : null;
      }
    };
    return api;
  }
  Cube.solved = () => Cube(SOLVED.slice());
  /* The state an algorithm solves: run it backwards from solved. */
  Cube.setup = function(alg){
    const p = parseMoves(alg);
    return p.ok ? Cube(applyMoves(SOLVED.slice(), invertMoves(p.moves))) : null;
  };

  const at = (c, i) => c.o[i];
  const allAre = (c, pairs) => pairs.every(([i, v]) => c.o[i] === v);

  const crossSolved      = c => allAre(c, CROSS);
  const f2lSlotSolved    = (c, s) => allAre(c, SLOTS[s]);
  const f2lDone          = c => crossSolved(c) && Object.keys(SLOTS).every(s => f2lSlotSolved(c, s));
  const ollDone          = c => { for(let i=0;i<9;i++) if(c.o[i] !== 0) return false; return true; };
  const ollEdgesDone     = c => [1,3,5,7].every(i => c.o[i] === 0);
  const isSolved         = c => { const o = c.o; for(let i=0;i<N;i++) if(o[i] !== SOLVED[i]) return false; return true; };
  function solvedUpToAUF(c){
    for(let k=0;k<4;k++) if(isSolved(Cube(applyPerm(c.o, powPerm(PERM.U, k))))) return k;
    return -1;
  }

  const yn = v => v === 0 ? "1" : "0";
  function ollEnc(c){
    const o = c.o;
    let s = OLL_TOP.map(i => yn(o[i])).join("");
    for(let r=0;r<3;r++){
      s += yn(o[OLL_L[r]]);
      for(let cc=0;cc<3;cc++) s += yn(o[r*3+cc]);
      s += yn(o[OLL_R[r]]);
    }
    return s + OLL_BOT.map(i => yn(o[i])).join("");
  }
  const pllRing = c => PLL_RING.map(i => LETTER[c.o[i]]).join("");

  function llPermutation(c){
    const o = c.o, out = {};
    for(const [slot, idx] of Object.entries(LL_CORNERS))
      out[slot] = HOME[idx.map(i=>o[i]).sort((a,b)=>a-b).join(",")];
    for(const [slot, idx] of Object.entries(LL_EDGES))
      out[slot] = HOME[idx.map(i=>o[i]).sort((a,b)=>a-b).join(",")];
    return out;
  }
  function pllArrows(c){
    const p = llPermutation(c), out = [];
    for(const [slot, home] of Object.entries(p))
      if(home && home !== slot) out.push([GRID[slot], GRID[home]]);
    return out;
  }

  /* Does `alg` solve `state`? Sweep holding angle x AUF: a learner who knows a
     different-but-correct algorithm, or holds the cube a quarter turn round,
     is right. A wrong algorithm still fails all sixteen. */
  function solvesCase(state, alg, predicate){
    const p = parseMoves(alg);
    if(!p.ok) return { ok:false, parse:p };
    for(let hold=0; hold<4; hold++){
      for(let auf=0; auf<4; auf++){
        let c = Cube(applyPerm(state.o, powPerm(PERM.y, hold)));
        c = Cube(applyPerm(c.raw, powPerm(PERM.U, auf)));
        const end = Cube(applyMoves(c.raw, p.moves));
        if(predicate(end)) return { ok:true, hold, auf, end,
                                    quarters:p.moves.reduce((n,m)=>n+m[1],0) };
      }
    }
    return { ok:false, end:Cube(applyMoves(state.raw, p.moves)),
             quarters:p.moves.reduce((n,m)=>n+m[1],0) };
  }

  return { N, SOLVED, LETTER, PERM, ROT24, applyPerm, composePerm, invertPerm,
           powPerm, orient, parseMoves, applyMoves, invertMoves, fmtMoves, Cube,
           crossSolved, f2lSlotSolved, f2lDone, ollDone, ollEdgesDone, isSolved,
           solvedUpToAUF, ollEnc, pllRing, llPermutation, pllArrows, solvesCase };
})();
/*== ENGINE:END ==*/

/* ---------------- storage: localStorage with in-memory fallback ---------------- */
const Store = (() => {
  let ok = true;
  try {
    localStorage.setItem("__t","1");
    localStorage.removeItem("__t");
  } catch (e) { ok = false; }
  const mem = {};
  return {
    ok,
    get(k){ try { return ok ? localStorage.getItem(k) : (mem[k] ?? null); } catch(e){ return mem[k] ?? null; } },
    set(k,v){ try { if(ok) localStorage.setItem(k,v); else mem[k]=v; } catch(e){ mem[k]=v; } },
    del(k){ try { if(ok) localStorage.removeItem(k); else delete mem[k]; } catch(e){ delete mem[k]; } }
  };
})();
if (!Store.ok) document.getElementById("storageWarn").classList.add("show");

/* ---------------- program data ---------------- */
const WEEKS = [
  { n:1, name:"Cross and F2L",  color:"var(--wk1)", light:true  },
  { n:2, name:"Last layer",     color:"var(--y)", light:true  },
  { n:3, name:"Recognition",    color:"var(--g)", light:false },
  { n:4, name:"Removing pauses",color:"var(--r)", light:false },
  { n:5, name:"Look-ahead",     color:"var(--b)", light:false },
  { n:6, name:"Stress test",    color:"var(--o)", light:false }
];

const DAYS = [
  {t:"Cross on the bottom",m:15,f:"Solve the white cross with white on the bottom face, not the top. This is the biggest habit change from the beginner method and it will feel wrong for a few days.",d:"10 crosses only. Scramble, solve the cross, check all four side colours match their centres. Read the bottom from the side stickers — don't turn the cube over.",
   w:"The beginner method builds the cross on top so you can watch it, then flips the cube over. CFOP skips the flip, which means every F2L pair afterwards drops straight into a slot you can already see. The price is that you're solving four pieces you can't look at directly, so you learn to read them from their side stickers instead. Turning the cube over to check is the habit to kill — it's the one thing that stops this becoming automatic."},
  {t:"What an F2L pair is",m:20,f:"A pair is one corner plus its matching edge, inserted into a slot together. The three base cases are all the same idea: get them next to each other, then put them in.",d:"Solve the cross, then insert one pair. Eight times. Don't do all four yet.",
   w:"The beginner method solves all four corners, then all four edges, with a separate algorithm for each. F2L does both at once, and that halving is where most of the time saving in CFOP actually comes from. Treat the three cases as one idea with three starting positions rather than three sequences to memorise — if you learn them as sequences you'll be stuck the first time a scramble hands you something slightly different."},
  {t:"All four slots",m:20,f:"Same three cases, now for every slot. Rotate the whole cube with y to bring the working slot to the front-right instead of learning mirrored versions.",d:"5 full F2L solves, untimed. Finish the last layer with your beginner method.",
   w:"There are mirrored algorithms for the other slots, but learning them now quadruples what you're carrying for no benefit. A y rotation costs a fraction of a second and lets you keep exactly one mental model. Speedcubers do eventually drop the rotations; that's an optimisation for later, not a foundation. The trap this week is drilling the front-right slot until it's smooth and discovering in week 4 that the back-left feels like a different puzzle."},
  {t:"Splitting up pairs",m:20,f:"The awkward cases: a corner and edge stuck together wrongly in a slot. Pull them out into the top layer with R U R', then treat it as a normal case.",d:"6 solves, deliberately hunting for slots that are already occupied.",
   w:"An occupied slot is the case beginners freeze on, and the fix is deliberately boring: don't try to repair it in place, just eject the contents and solve it as a case you already know. Two extra moves, no new memory. Hunting for these on purpose today is the point — in a real solve they turn up often enough that hesitation here costs more than the moves do."},
  {t:"Both pieces up top",m:20,f:"The most common situation in a real solve. Join the corner and edge first, then insert the finished pair.",d:"6 full F2L solves, untimed. Practise joining with R U' R' before inserting.",
   w:"This is the case you'll meet most often, so it's worth the most reps. Join first, then insert: two short moves. The failure mode is inserting the corner on its own and then going looking for the edge, which is the beginner method wearing a disguise and costs you the whole advantage of pairing."},
  {t:"Consolidation",m:20,f:"Cross and F2L end to end, beginner last layer. You're checking whether the intuition has stuck, not how fast it is.",d:"5 solves. Write down every case that took more than ten seconds to read.",
   w:"First time through the whole first two layers without stopping to think about which drill you're on. The written list matters more than the solves: tomorrow is built from it, and a specific list of four cases you actually stalled on is worth more than another hour of general solving. Resist timing yourself today — a stopwatch this early tells you nothing you can act on."},
  {t:"Review your gaps",m:15,f:"Only the cases you wrote down yesterday. Repetition on your actual weak spots beats another round of general solving.",d:"Set each case up by hand and solve it five times.",
   w:"Setting a case up by hand — scrambling deliberately so the case you want appears — is the single most useful practice technique in this programme, and it comes back in weeks 3 and 6. It lets you get twenty reps of the thing you're bad at in the time a random solve would give you one."},

  {t:"Orient the edges",m:15,f:"Two algorithms, and you're only making a yellow cross — ignore the corners completely. Line, L-shape, dot.",d:"Drill each ten times. The dot is just the other two run back to back, so don't memorise it separately.",
   w:"Full OLL is 57 algorithms. Splitting it into edges-then-corners brings it down to ten, and that split is the whole idea behind 2-look. Today you only care about the four edge stickers — the corners will be a mess afterwards and that is correct, not a mistake. Trying to fix corners at the same time is what makes people think OLL is hard."},
  {t:"Sune and Antisune",m:20,f:"The two cases where exactly one corner is already oriented. They are mirror images of each other, so learn them together.",d:"Apply each one repeatedly on a solved cube until it returns to solved — Sune comes back after six. 15 reps each.",
   w:"Two algorithms a day is the ceiling worth respecting; people who take on four forget all four by the weekend. Mirror pairs are the cheapest way to spend that budget, because the second one is mostly the first one reflected. Sune is the backbone of the whole corner set — several of the cases still to come are Sune with something wrapped around it, so time spent here pays off three more times."},
  {t:"T and Bowtie",m:20,f:"Two cases with two corners already oriented. Both use the wide r turn, which moves two layers at once.",d:"15 reps each. Check that your r is turning two layers, not slipping into a single R.",
   w:"The wide turn is the new mechanical idea here, and it's worth a minute of deliberate attention — a wide turn that slips into a single-layer turn produces a scrambled cube and a confusing debugging session. These two also share a shape: both are the same insert-and-restore idea seen from different angles."},
  {t:"H and Pi",m:20,f:"The two cases where no corner is oriented at all. From directly above they look identical.",d:"15 reps each, and practise telling them apart before you turn.",
   w:"Both show a bare yellow cross with nothing else on top, so the only thing separating them is where the yellow side stickers sit — H has them facing left and right in pairs, Pi does not. This is the one case pair where looking only at the top face cannot possibly work, which is why the diagrams below draw the rim as well. Misreading H as Pi is among the most common recognition errors, and it costs a whole extra algorithm to recover from."},
  {t:"Headlights, then all seven",m:20,f:"The last corner case, then the full set together. After today you can orient any last layer that appears.",d:"15 reps of Headlights, then set up random corner cases and solve them. Beginner PLL to finish.",
   w:"Headlights is the odd one out with no mirror partner, so it gets a day mostly to itself and then the session turns into consolidation. Mixing all seven immediately is the point: drilling them one at a time builds execution but not recognition, and recognition is what you'll actually be short of."},
  {t:"Permute the corners",m:20,f:"Two cases. Look for headlights — a pair of matching corner colours on one side — and hold that side at the back.",d:"Drill the 3-cycle until it's automatic. The diagonal case is long but rare, so just know where to find it.",
   w:"Corners before edges, because the edge algorithms assume the corners are already home. The headlights are the recognition cue: exactly one face will show two matching corner stickers, and that face goes at the back. If no face shows headlights anywhere, you have the diagonal case — that absence is itself the recognition, and it's the only case where seeing nothing is the answer."},
  {t:"U-perms",m:20,f:"Three edges cycling. Find the edge that's already correct, hold it at the back, then work out whether the cycle runs clockwise or anticlockwise.",d:"M is the middle slice, turned the same direction as L. Drill Ua and Ub ten times each.",
   w:"Ua and Ub move exactly the same three edges and differ only in which direction they travel, so the whole difficulty is telling them apart, not executing them. Find the solved edge first, put it at the back, then read the remaining three — the arrows in the algorithm list show which way each one goes. If you learn the M slice with your left index finger rather than a full grip change, these stay fast for the rest of your cubing life."},

  {t:"H and Z perms",m:15,f:"The two cases where edges swap rather than cycle. All sixteen algorithms are now covered.",d:"Ten reps each. H is symmetrical, so you can start it from any angle.",
   w:"H swaps the two opposite pairs, Z swaps the two adjacent pairs. H being fully symmetrical means there is no wrong angle to start it from, which makes it the one last-layer case you never have to line up first. That completes the set: sixteen algorithms that between them solve any scramble you will ever be handed."},
  {t:"First full CFOP solves",m:20,f:"Everything together for the first time. Slow is correct here — the milestone is finishing without falling back on the beginner method, not the time.",d:"3 complete solves, notes allowed.",
   w:"Notes are allowed today on purpose. What's being tested is whether the pieces connect into one method, not whether you've finished memorising — that's the rest of this week. Expect this to feel slower than your beginner method and expect that to last a while. Everyone goes through a stretch where the new method is worse than the old one; it's a phase, not a signal to go back."},
  {t:"OLL recognition",m:15,f:"Almost every failed solve is a misread case, not a forgotten algorithm. So train the reading, not the turning.",d:"Set up a random OLL, name it out loud within three seconds, then execute. 15 reps.",
   w:"By now the algorithms are mostly in your hands and the bottleneck has moved to your eyes. Recognition and execution are separate skills, and practising full solves trains them together at whatever ratio the scramble happens to give you — which is far too little recognition. Naming the case out loud forces the recognition step to actually finish instead of blurring into the turning."},
  {t:"OLL recognition",m:15,f:"Same drill. You're building the reflex that turns a pattern into a name without conscious effort.",d:"15 reps. If you can't name it in three seconds, look it up and redo that case immediately.",
   w:"The three-second rule is the useful part. Sitting and puzzling it out eventually gets you the right answer and teaches you nothing, because in a real solve you won't have the time. Look it up, redo it straight away, and let the immediate correction do the work. The shift you want is from \"two corners point that way, so it must be...\" to simply seeing Sune."},
  {t:"PLL recognition",m:15,f:"Now the same for PLL, and from all four angles. The hard part is spotting a Ua while standing on the wrong side of it.",d:"Set up a case, rotate the cube to a random angle, name it. 15 reps.",
   w:"PLL recognition is harder than OLL because rotating the cube changes how the case looks without changing what it is, and there's no yellow-versus-not shortcut to fall back on. Rotating deliberately before you look is the whole drill. In a real solve the last layer arrives at whatever angle F2L happened to leave it, which is essentially random."},
  {t:"PLL recognition",m:15,f:"Corners first, then edges. Keep rotating before you look — recognising only from the front is the most common hidden weakness.",d:"15 reps, then 2 full solves.",
   w:"Front-only recognition hides well because it doesn't feel like a weakness: you read everything fine while practising, then stall in solves and blame execution. If one angle is consistently slower, drill that angle on its own rather than continuing to sample randomly. Check both stages explicitly — headlights or no headlights for the corners, then which edge is already home for the edges."},
  {t:"Notes closed",m:20,f:"The gate for the whole programme. If you can't get through a solve without opening your notes, repeat week 3 rather than moving on — nothing later works without this.",d:"4 full solves, notes shut. Mark which case sent you back to them.",
   w:"This is a real gate, not encouragement. Everything from week 4 onward trains speed and fluency, and neither is trainable while you're still looking things up — you'd be practising the lookup. Repeating a week here is much cheaper than pushing on and rebuilding later. Nobody is watching, and the programme is not a schedule you can fall behind on."},

  {t:"Plan the cross",m:20,f:"Take 30 seconds before each solve and plan all four cross edges before you touch the cube. Then execute without re-planning.",d:"5 solves. You're not racing, so use the full 30 seconds.",
   w:"In competition this is the 15-second inspection; here it's just a habit. Planning the cross in advance means the solve opens with continuous turning instead of a stop-start search, and it's the cheapest speed improvement available — no new algorithms, no faster hands. Use the whole 30 seconds even when you think you've got it; the goal is a complete plan, not a quick one."},
  {t:"Plan the cross",m:20,f:"Again. Most people can plan two edges immediately and stall on the third — that's the part worth the time.",d:"5 solves.",
   w:"Two edges is roughly what fits in visual memory without effort. The third and fourth need you to actually track pieces through the moves you've already planned, which is the skill being built. If you lose the plan halfway, start the planning again rather than solving what you can remember."},
  {t:"Plan the cross",m:20,f:"By the third session you should be finishing the cross without stopping to look for pieces.",d:"5 solves, then check: did you pause mid-cross at all?",
   w:"A pause mid-cross means the plan was incomplete, not that your hands were slow. That distinction matters because it tells you what to fix. Planning also sets up the next habit directly: with the cross already handled, your eyes are free during execution, which is what week 5 exploits."},
  {t:"Slot flexibility",m:20,f:"After the cross, solve the easiest pair you can see rather than always going to the front-right slot. This single habit is what stops you getting stuck.",d:"5 solves. Before each pair, scan all four slots and pick deliberately.",
   w:"Insisting on a fixed slot order means that on most scrambles you're solving a hard case when an easy one was sitting right there. Choosing costs nothing and removes most of the awkward cases from your solves entirely. This is probably the highest-value habit in the second half of the programme, and it's a decision, not a technique."},
  {t:"Slot flexibility",m:20,f:"Keep choosing. The goal is that no scramble ever presents you with a slot you feel obliged to solve.",d:"5 solves.",
   w:"The word to watch is \"obliged\". If you notice yourself going to a slot because it's next rather than because it's easiest, you've slipped back into a fixed order without deciding to."},
  {t:"Slot flexibility",m:20,f:"Last session on choice. You should be picking a slot without thinking of it as a decision.",d:"5 solves.",
   w:"Deliberate choice becoming automatic choice is the transition here. Once it's automatic you stop spending attention on it, which frees that attention for the tracking work in week 5."},
  {t:"Checkpoint",m:20,f:"A read on where the remaining friction lives before the last two weeks.",d:"5 full solves. Note where you paused longest — cross, F2L, or last layer.",
   w:"Diagnostic, not a test. Two weeks of specific work are coming and they'll be worth more if aimed at something real. Most people find the answer is F2L, simply because it's the longest phase and the least algorithmic — but check rather than assume, because if it's actually last-layer recognition then week 5's look-ahead work is aimed at the wrong problem."},

  {t:"Look-ahead",m:20,f:"While inserting one pair, keep your eyes on the next pair's pieces. Turn at half speed so your eyes can get ahead of your hands. This feels counterproductive and is the most effective drill in the programme.",d:"4 solves at deliberately slow turning speed. No fast turning today at all.",
   w:"Fast solving isn't fast turning — it's turning without stopping, and the pauses between phases cost far more than the moves themselves. You can only remove a pause by knowing what comes next before you arrive, which means looking ahead while your hands are busy. Slowing down is what makes room for that, which is why the drill feels wrong and works anyway. Almost every speedcuber names this as the thing that broke their plateau."},
  {t:"Look-ahead",m:20,f:"Still slow. If you catch yourself speeding up, you've stopped tracking and gone back to reacting.",d:"4 slow solves.",
   w:"Speeding up is the reliable symptom: turning fast is comfortable precisely because it needs no tracking. Treat the moment you notice it as information rather than a failure, slow back down, and carry on."},
  {t:"Look-ahead",m:20,f:"Third session. You should be finding the next pair before the current insertion finishes.",d:"4 slow solves, then 1 at normal speed to compare.",
   w:"The comparison solve at the end is the interesting one. Most people find their normal-speed time has improved even though they've spent three sessions deliberately turning slowly — which is the clearest evidence available that pauses, not turning speed, were the bottleneck."},
  {t:"No stopping",m:20,f:"Untimed solves with a single rule: never pause. Pausing is the thing you're trying to remove, so treat each one as a bug to fix.",d:"4 solves. If you pause, finish the solve, then set that exact case up and drill it five times.",
   w:"Same target as look-ahead, approached from the other end: instead of building the skill that prevents pauses, hunt the pauses that remain. The repair routine is what makes it work — a pause tells you exactly which case is underlearned, and drilling it immediately closes the gap while you still remember what it was."},
  {t:"No stopping",m:20,f:"Same rule. The list of cases that make you stop should be getting shorter each session.",d:"4 solves, same repair routine.",
   w:"A shrinking list is the measure of progress this week, and it's a better one than time because it points at something you can act on. If the list isn't shrinking, the cases on it are probably recognition problems rather than execution problems — go back to naming them out loud."},
  {t:"No stopping",m:20,f:"Last session under the rule. Any case still causing a pause goes on your shortlist for week 6.",d:"4 solves. Write down anything that still stops you.",
   w:"Whatever survives three sessions of targeted repair is genuinely stubborn and deserves the concentrated treatment in days 39 and 40. Keep the list short — two cases handled properly beats eight handled loosely."},
  {t:"Checkpoint",m:20,f:"Consistency measured properly: no notes, no pauses, any scramble.",d:"6 solves. Log how many were completely clean.",
   w:"Clean solves out of six is a better measure than average time, because at this stage your average is dominated by the one solve that went wrong. Consistency is also what actually improves from here — the ceiling on your good solves moves slowly, but the floor comes up fast."},

  {t:"Under distraction",m:20,f:"Consistency means the method survives conditions that aren't ideal. Put a timer on, or a podcast, or solve standing up.",d:"5 solves with something competing for your attention.",
   w:"A method that only works when you're concentrating is not finished being learned. Distraction is a cheap way to find out which parts still need conscious attention, because those are exactly the parts that break first. Anything that occupies you a bit works — the specific distraction doesn't matter."},
  {t:"Under distraction",m:20,f:"Again, with a different distraction than yesterday. You're testing the method, not your concentration.",d:"5 solves.",
   w:"Varying it stops you adapting to one particular kind of interference, which would defeat the point. A timer competes for attention differently than a conversation does."},
  {t:"Under distraction",m:20,f:"Final session. If accuracy holds here, it will hold anywhere.",d:"5 solves.",
   w:"Holding up under interference is a stronger result than a good time under ideal conditions, and it's the one that transfers to solving in front of other people."},
  {t:"Your weakest two",m:20,f:"Pick the two cases that have given you the most trouble across all six weeks. Nothing else today.",d:"20 reps of each, set up by hand.",
   w:"You've been keeping the list since day 6. Narrow, concentrated repetition is what actually fixes a stubborn case; general solving gives you one rep of it every few minutes and lets you avoid it the rest of the time. Two is the right number — the temptation is to pick six and give none of them enough attention."},
  {t:"Your weakest two",m:20,f:"The same two. Two days of narrow focus fixes things that six weeks of general solving didn't.",d:"20 reps each, then 2 full solves to check they hold in context.",
   w:"The full solves at the end matter: a case can be solid in isolation and still fall apart when it arrives unannounced after F2L. If that happens, the problem was recognition rather than execution, and it needs the naming drill rather than more reps."},
  {t:"Ten in a row",m:20,f:"The final test of the programme. Any scramble, no notes, no fallback to the beginner method.",d:"10 consecutive solves. Target is 10 out of 10 clean.",
   w:"Ten consecutive solves is long enough that you can't hold concentration throughout, which is the point — it measures the method rather than your focus on the day. Eight or nine clean is a genuine pass; if you get five, the programme still worked, and the fix is more solving rather than more learning."},
  {t:"Where next",m:20,f:"You have a complete method that solves any scramble. Stopping here is a perfectly good outcome. If you want more, full PLL is the natural next step — a few algorithms at a time, not all 21 at once.",d:"Free solving. Decide whether you're done or expanding.",
   w:"Two-look CFOP with good look-ahead comfortably beats one-look CFOP with pauses, so there is nothing embarrassing about staying here — plenty of people solve in well under a minute on exactly these sixteen algorithms. If you do expand, full PLL is the better next step than full OLL: 21 algorithms rather than 57, and it removes a whole recognition step from every solve. Learn them a few at a time and keep using the ones you know in between."}
];

/* Diagrams are plan views of the last layer with the front face at the bottom.
   OLL `e` is 21 facelets: 3 back-rim, then (left, u0, u1, u2, right) per row,
   then 3 front-rim. 1 = yellow facing that way. Every string below was generated
   from a cube simulator by applying each algorithm's inverse to a solved cube,
   so the diagram always matches what the algorithm actually solves.
   PLL `r` is the 12 side stickers clockwise from the back-left corner, and `x`
   lists the piece movements as [from, to] over the 3x3 grid indexed 0-8. */
const ALGS = {
  cross: { label:"Cross", rows:[] },
  f2l: { label:"F2L", rows:[
    {n:"Basic insert · right",s:"Corner above the slot, edge on the right",a:"R U R'",
     note:"The atom of F2L. Everything else is a setup that turns your case into this one. Watch what it does: the corner drops in and the edge follows it."},
    {n:"Basic insert · front",s:"Corner above the slot, edge on the left",a:"y' R' U' R",
     note:"The mirror of the one above. Rotating with y' rather than learning a separate left-hand version keeps you carrying one idea instead of two."},
    {n:"Pair, then insert · right",s:"Both pieces up top, corner facing front",a:"U R U' R'",
     note:"Separate, pair, insert — the three-phase idea. The U at the front is the pairing move; the rest is the basic insert."},
    {n:"Pair, then insert · left",s:"Both pieces up top, mirrored",a:"y' U' R' U R",
     note:"Same three phases on the other side. If you find yourself hunting for a third and fourth variant, you're memorising instead of seeing."},
    {n:"Sexy move",s:"The trigger everything is built from",a:"R U R' U'",
     note:"Not an F2L case — a building block worth knowing by name, because tutorials and algorithms below are described in terms of it. Six repetitions on a solved cube return it to solved, which is a good way to feel how it works."},
    {n:"Sledgehammer",s:"The other common trigger",a:"R' F R F'",
     note:"The second piece of vocabulary. Once you can see sexy moves and sledgehammers inside longer algorithms, the last-layer set stops looking arbitrary."}
  ]},
  oll: { label:"OLL · 10", rows:[
    {n:"Line",s:"Edges — bar running left to right",a:"F R U R' U' F'",edges:true,
     e:"010100100111010010010",
     note:"Hold the bar horizontally, across your view. You are only orienting edges here, so the corners will still be a mess afterwards — that is correct, not a mistake. This is the algorithm every other edge case is built from."},
    {n:"L-shape",s:"Edges — L occupying front and right",a:"f R U R' U' f'",edges:true,
     e:"010100101011010110000",
     note:"Hold the L so its two oriented edges sit at the front and the right. This holding is specific to this algorithm: the common variant F U R U' R' F' solves the same case held the opposite way, so don't mix an algorithm from one source with a picture from another."},
    {n:"Dot",s:"Edges — none oriented; run the other two in sequence",a:"F R U R' U' F' · f R U R' U' f'",edges:true,
     e:"011100001010110000011",
     note:"No separate algorithm needed and no separate holding either — this one works from any angle. Run the Line algorithm, which turns the dot into an L, then run the L algorithm. Don't memorise it as a third sequence."},
    {n:"Sune",s:"Corners — one oriented, at the front left",a:"R U R' U R U2 R'",
     e:"100001010111001100001",
     note:"The backbone of the corner set. Hold the single oriented corner at the front left. It twists exactly three corners, which is why six repetitions on a solved cube bring it back to solved — a good drill that needs no scrambling."},
    {n:"Antisune",s:"Corners — one oriented, at the back right",a:"R U2 R' U' R U' R'",
     e:"000101100111000101100",
     note:"Sune's mirror, and the other one-corner case. Learn it immediately after Sune while the shape of that algorithm is still fresh; taken together they are much less than two algorithms' worth of work."},
    {n:"T / Chameleon",s:"Corners — two oriented, both on the right",a:"r U R' U' r' F R F'",
     e:"100001100111000110100",
     note:"The lowercase r is a wide turn: it moves the right layer and the middle slice together. A wide turn that slips into a single-layer turn scrambles the cube in a confusing way, so check your grip before you start."},
    {n:"L / Bowtie",s:"Corners — two oriented, diagonally opposite",a:"F' r U R' U' r' F R",
     e:"000101100111001100001",
     note:"The other wide-turn case, and the only corner case with its two oriented corners diagonally across from each other. Some sources give this algorithm with a y rotation in front; the diagram here matches the algorithm as written."},
    {n:"Headlights",s:"Corners — two oriented, both at the back",a:"R2 D R' U2 R D' R' U2 R'",
     e:"000011100111000100101",
     note:"The odd one out with no mirror partner. It uses D, which no other last-layer algorithm here does, so it tends to feel unfamiliar for longer than the others — worth extra repetitions."},
    {n:"H",s:"Corners — none oriented; yellow on left and right",a:"R U R' U R U' R' U R U2 R'",
     e:"000101010111010101000",
     note:"Looks identical to Pi from directly above: a bare yellow cross either way. What separates them is the rim — H shows yellow in matching pairs on the left and right faces. It is essentially Sune done three times."},
    {n:"Pi",s:"Corners — none oriented; rim pattern differs from H",
     a:"R U2 R2 U' R2 U' R2 U2 R",
     e:"001101000111010100001",
     note:"The other no-corners case. Compare the rim against H before you commit: this is the one case pair where reading only the top face cannot possibly tell you which you have, and confusing them costs a whole extra algorithm to recover."}
  ]},
  pll: { label:"PLL · 6", rows:[
    {n:"Corner 3-cycle",s:"Corners — headlights at the back",a:"R' F R' B2 R F' R' B2 R2",
     r:"RBRGROBGGOOB",x:[[0,2],[2,8],[8,0]],
     note:"Not a two-corner swap — swapping just two corners is impossible on a cube. Three corners rotate positions and one stays put. Find the face showing two matching corner stickers (the headlights) and put it at the back. This one leaves the edges completely alone, which keeps the two-stage picture clean."},
    {n:"Diagonal swap",s:"Corners — no headlights anywhere",a:"F R U' R' U' R U R' F' R U R' U' R' F R F'",
     r:"GOBRROBGGOBR",x:[[0,8],[8,0],[1,3],[3,1]],
     note:"The Y-perm. Recognition is the absence of a cue: check all four faces, and if none shows headlights, this is your case. Long but it works from any angle, so there is no holding to get wrong. It also swaps two edges, which is harmless because edges are the next step anyway."},
    {n:"Ua",s:"Edges — solved edge at the back, cycle runs one way",a:"M2 U M U2 M' U M2",
     r:"BBBRORGRGOGO",x:[[7,5],[5,3],[3,7]],
     note:"Three edges rotate positions; the fourth is already home and goes at the back. Ua and Ub move exactly the same three edges and differ only in direction, so the whole difficulty is telling them apart. Follow the arrows: here the front edge travels to the right."},
    {n:"Ub",s:"Edges — solved edge at the back, cycle runs the other way",a:"M2 U' M U2 M' U' M2",
     r:"BBBRGRGOGORO",x:[[7,3],[3,5],[5,7]],
     note:"The mirror of Ua, and the only difference in the algorithm is which way the U turns go. Here the front edge travels to the left. If you keep confusing the two, name the direction out loud before you start turning."},
    {n:"H",s:"Edges — both opposite pairs swap",a:"M2 U M2 U2 M2 U M2",
     r:"BGBRORGBGORO",x:[[1,7],[7,1],[3,5],[5,3]],
     note:"Front swaps with back, left swaps with right. Fully symmetrical, so there is no wrong angle to start from — the one last-layer case you never have to line up first. Also the easiest algorithm here to execute once the M slice is comfortable."},
    {n:"Z",s:"Edges — both adjacent pairs swap",a:"M2 U M2 U M' U2 M2 U2 M' U2",
     r:"BOBRGRGRGOBO",x:[[1,3],[3,1],[7,5],[5,7]],
     note:"The other swap case: neighbours trade rather than opposites. Some published versions of this algorithm finish a quarter turn out, needing a final U to line the layer up — if yours does, that is normal and not a mistake."}
  ]}
};

const STAGES = {
  cross: {h:"Cross", p:[
    "Four white edges on the bottom face, each matching its side centre. It is the one part of CFOP with no algorithms at all, and the one people under-practise most.",
    "The break from the beginner method is that the cross goes on the <b>bottom</b>, not the top. The beginner method builds it where you can watch it and then flips the cube; CFOP skips the flip so that every F2L pair afterwards drops into a slot you can already see. The cost is that you solve four pieces you can't look at directly, reading them from their side stickers instead.",
    "Any cross can be solved in eight moves or fewer, so if you are using fifteen the problem is planning rather than technique. The skill worth building is planning all four edges before you touch the cube — that alone removes the longest pause in most solves."
  ], bad:[
    "Turning the cube over mid-solve to check the cross.",
    "Solving the four edges one at a time instead of looking at how they interact.",
    "Skipping cross practice because it feels too easy to be worth a session."
  ]},
  f2l: {h:"First two layers", p:[
    "Corner and edge together, four times, filling the four slots between the cross and the last layer. This is the longest phase of the solve and the one where the time actually goes.",
    "The beginner method solves all four corners and then all four edges, with a separate algorithm each time. F2L does both at once. That halving is where most of CFOP's advantage comes from — more than the last-layer algorithms, which get all the attention.",
    "The method is three phases: <b>separate</b> the corner and edge into the top layer, <b>pair</b> them so they sit together, then <b>insert</b> the pair in one trigger. Learn it as that idea rather than as a list of sequences, because the full case list runs to 41 and memorising it is neither necessary nor recommended at this stage.",
    "Fair warning: your times will get <em>worse</em> when you start F2L, typically for a week or two. Everyone goes through it. It is the single most common point at which people give up and go back to the beginner method, which is why it is worth naming in advance."
  ], bad:[
    "Inserting the corner first and then going to look for its edge — that is the beginner method wearing a disguise.",
    "Always solving the front-right slot, so the other three stay unfamiliar.",
    "Breaking up a pair you have already solved.",
    "Learning mirrored algorithms for every slot instead of rotating with y."
  ]},
  oll: {h:"Orienting the last layer", p:[
    "Make the whole top face yellow, without caring where any piece ends up. Full OLL is 57 algorithms; splitting it into edges first, then corners, brings it down to ten. That split is what 2-look means.",
    "Stage one uses two algorithms and ignores the corners completely — you are only making a yellow cross. Stage two uses seven and orients the corners without disturbing the cross you just made.",
    "The seven corner cases sort themselves by how many corners are already yellow: two cases with one corner (Sune, Antisune), three with two (T, Bowtie, Headlights), and two with none (H, Pi). Counting first turns recognition from a memory problem into a much smaller lookup."
  ], bad:[
    "Trying to fix corners during the edge step.",
    "Reading H and Pi off the top face alone — they are identical up there and only the side stickers separate them.",
    "Taking on more than two new algorithms in a session. It reliably produces four half-learned ones."
  ]},
  pll: {h:"Permuting the last layer", p:[
    "Everything is yellow on top; now move the pieces to where they belong. Full PLL is 21 algorithms, and the two-look split brings it to six: corners first, then edges.",
    "Corners come first because the edge algorithms assume the corners are already home. There are only two corner cases, and they are told apart by <b>headlights</b> — a face showing two matching corner stickers. Find headlights and hold that face at the back; find none anywhere and you have the diagonal case.",
    "The four edge cases split the same way: two where three edges cycle (Ua and Ub, distinguished only by direction) and two where pairs swap (H for opposites, Z for neighbours). All four are built from the M slice, so time spent on that finger trick pays back across the whole set."
  ], bad:[
    "Doing edges before corners.",
    "Recognising cases only from the front, then stalling when the last layer arrives at a different angle.",
    "Confusing Ua and Ub — they move the same three pieces and differ only in which way round."
  ]}
};

const READING = [
  {t:"J Perm",u:"https://jperm.net/3x3/cfop",d:"The clearest free CFOP tutorials anywhere, plus algorithm trainers. Start here if you want video."},
  {t:"CubeSkills",u:"https://www.cubeskills.com/",d:"Feliks Zemdegs' site. Printable algorithm sheets and good blog posts on how to practise."},
  {t:"Speedsolving wiki",u:"https://www.speedsolving.com/wiki/index.php/CFOP",d:"Reference rather than tutorial — case lists, terminology, and the full 41-case F2L set when you want it."},
  {t:"Full PLL",u:"https://www.speedsolving.com/wiki/index.php/PLL",d:"The natural next step after this programme. 21 algorithms; learn a few at a time."}
];

/* ---------------- scrambles ----------------
   A seeded random-move scrambler. The same seed always produces the same
   scramble, so "day 12, solve 3" is the same cube today and next month, on any
   device, with nothing stored. Note this is random-MOVE, not the random-STATE
   scrambling the WCA uses for competition — that needs a full solver. Measured
   over 3000 seeds, 20 moves leaves on average 8.3 of the 48 non-centre stickers
   matching, which is what a genuinely random state gives, so it is more than
   good enough to practise on. */
function hashSeed(str){                       // FNV-1a
  let h = 2166136261;
  for(let i=0;i<str.length;i++){ h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
function rngFrom(str){                        // mulberry32
  let a = hashSeed(str);
  return function(){
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), a | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const FACES = ["U","R","F","D","L","B"], SUFFIX = ["","'","2"];
const AXIS = {U:0,D:0,R:1,L:1,F:2,B:2};
function makeScramble(seed, n){
  const rnd = rngFrom(seed), out = [];
  let guard = 0;
  while(out.length < (n||20) && guard++ < 500){
    const f = FACES[Math.floor(rnd()*6)];
    if(out.length && out[out.length-1][0] === f) continue;              // no R then R'
    if(out.length > 1 && AXIS[out[out.length-1][0]] === AXIS[f]
       && AXIS[out[out.length-2][0]] === AXIS[f]) continue;             // no R L R
    out.push(f + SUFFIX[Math.floor(rnd()*3)]);
  }
  return out.join(" ");
}

/* ---------------- cross solver ----------------
   Only the four white edges matter, so the search space is tiny: 12 slots and a
   flip for each of 4 pieces. We breadth-first the whole thing once from solved,
   then walk downhill from the scrambled state, which yields a provably optimal
   cross (never more than 8 moves). Move tables were generated from a verified
   cube simulator rather than written by hand. */
const EMOVE = {
  U:[[1,2,3,0,4,5,6,7,8,9,10,11],[0,0,0,0,0,0,0,0,0,0,0,0]],
  R:[[11,1,2,3,8,5,6,7,0,9,10,4],[0,0,0,0,0,0,0,0,0,0,0,0]],
  F:[[0,8,2,3,4,9,6,7,5,1,10,11],[0,1,0,0,0,1,0,0,1,1,0,0]],
  D:[[0,1,2,3,7,4,5,6,8,9,10,11],[0,0,0,0,0,0,0,0,0,0,0,0]],
  L:[[0,1,9,3,4,5,10,7,8,6,2,11],[0,0,0,0,0,0,0,0,0,0,0,0]],
  B:[[0,1,2,10,4,5,6,11,8,9,7,3],[0,0,0,1,0,0,0,1,0,0,1,1]]
};
/* EMOVE above covers only the six faces, so a scramble or a learner-typed
   solution containing M, a wide turn or a rotation would throw. Derive the
   missing tables from the facelet engine, which knows all eighteen: for each
   edge slot, find where its stickers land and whether they swapped. The six
   face tables are re-derived too and asserted against the hand-generated ones
   above, so this cannot drift from the version the BFS was verified with. */
const EDGE_FACELETS = [[5,10],[7,19],[3,37],[1,46],[32,16],[28,25],
                       [30,43],[34,52],[23,12],[21,41],[50,39],[48,14]];
(function extendEdgeMoves(){
  const slotOf = new Map();
  EDGE_FACELETS.forEach(([a,b],s)=>{ slotOf.set(a,[s,0]); slotOf.set(b,[s,1]); });
  const derive = perm => {
    const dest = new Array(12), flip = new Array(12);
    EDGE_FACELETS.forEach(([a],j)=>{
      const [from, swapped] = slotOf.get(perm[a]);
      dest[from] = j; flip[from] = swapped;
    });
    return [dest, flip];
  };
  for(const m of Object.keys(CUBE.PERM)){
    const [dest, flip] = derive(CUBE.PERM[m]);
    if(EMOVE[m]){
      const same = EMOVE[m][0].every((v,i)=>v===dest[i]) && EMOVE[m][1].every((v,i)=>v===flip[i]);
      if(!same) console.error("edge table for " + m + " disagrees with the engine");
    } else {
      EMOVE[m] = [dest, flip];
    }
  }
})();

const CROSS_HOME = [4,5,6,7];                 // DR, DF, DL, DB
const SOLVED_CROSS = encodeCross([4,5,6,7],[0,0,0,0]);
function encodeCross(pos, flip){
  return ((((pos[0]*12 + pos[1])*12 + pos[2])*12 + pos[3]) << 4)
       | (flip[0] | (flip[1]<<1) | (flip[2]<<2) | (flip[3]<<3));
}
function turnCross(pos, flip, face, times){
  const [dest, fl] = EMOVE[face];
  for(let t=0;t<times;t++)
    for(let i=0;i<4;i++){ flip[i] ^= fl[pos[i]]; pos[i] = dest[pos[i]]; }
}
/* All 18 moves, as [face, quarter-turns, printed name]. Note the name is not
   SUFFIX[t-1]: two quarter turns prints "2" and three prints "'", so that
   parseAlg(name) round-trips back to t. */
const turnName = (f,t) => f + (t === 2 ? "2" : t === 3 ? "'" : "");
const MOVES18 = [];
FACES.forEach(f => [1,2,3].forEach(t => MOVES18.push([f, t, turnName(f,t)])));

let crossDist = null;
function buildCrossTable(){
  if(crossDist) return crossDist;
  const N = 12*12*12*12*16;
  const dist = new Uint8Array(N).fill(255);
  dist[SOLVED_CROSS] = 0;
  let frontier = [[[4,5,6,7],[0,0,0,0]]];
  for(let d=0; frontier.length; d++){
    const next = [];
    for(const [p,f] of frontier){
      for(const [face,times] of MOVES18){
        const np = p.slice(), nf = f.slice();
        turnCross(np, nf, face, times);
        const k = encodeCross(np, nf);
        if(dist[k] === 255){ dist[k] = d+1; next.push([np,nf]); }
      }
    }
    frontier = next;
  }
  crossDist = dist;
  return dist;
}
/* Read the four white edges out of an oriented cube.

   This used to walk the 4-edge model directly from solved, which was fine for
   generated scrambles but wrong the moment a whole-cube rotation appeared: the
   edge model has no centres, so it cannot be centre-relative, and after a `y`
   it disagrees with the facelet engine about whether the cross is solved. Going
   through `orient()` puts both models in the same frame. Verified identical to
   the old path on 500 face-only scrambles. */
const CROSS_COLOURS = [[3,1],[3,2],[3,4],[3,5]];        // DR, DF, DL, DB
function crossStateOf(cube){
  const o = cube.o, pos = [-1,-1,-1,-1], flip = [0,0,0,0];
  EDGE_FACELETS.forEach(([a,b], slot)=>{
    const ca = o[a], cb = o[b];
    for(let i=0;i<4;i++){
      const [w0,w1] = CROSS_COLOURS[i];
      if((ca===w0 && cb===w1) || (ca===w1 && cb===w0)){
        pos[i] = slot;
        flip[i] = ca === 3 ? 0 : 1;                     // white on the slot's first facelet
      }
    }
  });
  return [pos, flip];
}
function crossStateAfter(alg){
  const c = CUBE.Cube.solved().apply(alg);
  return c ? crossStateOf(c) : [CROSS_HOME.slice(), [0,0,0,0]];
}

/* Frame note: because crossStateOf reads an *oriented* cube, a solution is
   expressed in the canonical frame (white down, green front). For every input
   this page actually produces that is a distinction without a difference —
   makeScramble emits face turns only, which never move the centres, so orient()
   is the identity there. It matters only for a hand-typed algorithm containing
   a whole-cube rotation, and T4 grades those by execution rather than by
   comparing against this solver's output. */
function solveCross(alg){
  const dist = buildCrossTable();
  let [pos, flip] = crossStateAfter(alg);
  const out = [];
  let d = dist[encodeCross(pos, flip)];
  while(d > 0){
    for(const [face, times, name] of MOVES18){
      const np = pos.slice(), nf = flip.slice();
      turnCross(np, nf, face, times);
      const nd = dist[encodeCross(np, nf)];
      if(nd === d-1){ out.push(name); pos = np; flip = nf; d = nd; break; }
    }
  }
  return out;
}

/* ---------------- notation helpers ---------------- */
/* Both of these now delegate to the engine's strict tokenizer. The old regex
   here silently skipped anything it did not recognise, so `y' R' U' R` parsed
   as `R' U' R` — a whole-cube rotation dropped without a word. That was latent
   only because invertAlg is called just on rows that have a diagram, and the
   two rotation-bearing algorithms are F2L rows, which have none. */
function parseAlg(alg){
  const p = CUBE.parseMoves(alg);
  return p.ok ? p.moves : [];
}
/* The setup for a case is simply the algorithm run backwards: apply it to a
   solved cube and you get exactly the case the algorithm solves. */
function invertAlg(alg){
  const p = CUBE.parseMoves(alg);
  return p.ok ? CUBE.fmtMoves(CUBE.invertMoves(p.moves)) : "";
}

/* ---------------- state ---------------- */
const P_KEY = "cfop.profiles", A_KEY = "cfop.active";
let profiles = JSON.parse(Store.get(P_KEY) || 'null') || ["Me"];
let active = Store.get(A_KEY) || profiles[0];
if (!profiles.includes(active)) active = profiles[0];
let done = new Set();
let view = 0;

const dKey = name => "cfop.done." + name;
function loadProgress(){
  done = new Set(JSON.parse(Store.get(dKey(active)) || "[]"));
  view = firstUndone();
}
function saveProgress(){ Store.set(dKey(active), JSON.stringify([...done])); }
function saveProfiles(){ Store.set(P_KEY, JSON.stringify(profiles)); Store.set(A_KEY, active); }
function firstUndone(){
  for (let i=0;i<DAYS.length;i++) if(!done.has(i)) return i;
  return DAYS.length-1;
}
const weekOf = i => WEEKS[Math.floor(i/7)];

/* ---------------- rendering ---------------- */
const $ = id => document.getElementById(id);

function renderProfiles(){
  const sel = $("profile");
  sel.innerHTML = "";
  profiles.forEach(p=>{
    const o = document.createElement("option");
    o.value = p; o.textContent = p; if(p===active) o.selected = true;
    sel.appendChild(o);
  });
}

function renderSession(){
  const day = DAYS[view], wk = weekOf(view);
  $("eyebrow").innerHTML =
    `<span class="chip" style="background:${wk.color}"></span>Week ${wk.n} — ${wk.name}`;
  $("card").style.setProperty("--accent", wk.color);
  $("daynum").textContent = "Day " + String(view+1).padStart(2,"0") + " of 42";
  $("title").textContent = day.t;
  $("mins").textContent = day.m + " min";
  $("focus").textContent = day.f;
  $("drill").textContent = day.d;
  $("why").textContent = day.w;

  const isDone = done.has(view);
  const btn = $("mark");
  btn.textContent = isDone ? "Completed — undo" : "Mark day complete";
  btn.classList.toggle("done", isDone);

  $("prev").disabled = view === 0;
  $("next").disabled = view === DAYS.length-1;

  renderScramble();
}

/* ---------------- scramble panel ---------------- */
let solveN = 1, seedOverride = "", scrambleView = -1;
function currentSeed(){
  const custom = seedOverride.trim();
  return custom || ("day-" + String(view+1).padStart(2,"0") + "-" + solveN);
}
function renderScramble(){
  if(scrambleView !== view){ scrambleView = view; solveN = 1; seedOverride = ""; }
  const seed = currentSeed();
  $("scrambleMoves").textContent = makeScramble(seed, 20);
  if($("seedInput").value !== seed) $("seedInput").value = seed;
  $("crossOut").classList.remove("show");
  $("crossOut").innerHTML = "";
}
function showCross(){
  const box = $("crossOut");
  if(box.classList.contains("show")){ box.classList.remove("show"); return; }
  const moves = solveCross($("scrambleMoves").textContent);
  box.innerHTML = moves.length
    ? `Cross: <b>${moves.join(" ")}</b><i>${moves.length} move${moves.length===1?"":"s"} — apply this after the scramble, then practise F2L from there. It is the shortest cross that exists for this scramble, so don't treat it as the one you should have found.</i>`
    : `Cross: <b>already solved</b><i>This scramble happens to leave the cross intact.</i>`;
  box.classList.add("show");
}

function renderGrid(){
  const host = $("weeks");
  host.innerHTML = "";
  WEEKS.forEach((wk,wi)=>{
    const row = document.createElement("div");
    row.className = "week";
    const lab = document.createElement("div");
    lab.className = "wlabel";
    lab.textContent = "Wk " + wk.n;
    lab.title = wk.name;
    row.appendChild(lab);
    for(let d=0; d<7; d++){
      const i = wi*7 + d;
      const b = document.createElement("button");
      b.className = "sticker";
      b.style.setProperty("--c", wk.color);
      if(done.has(i)) b.classList.add("done");
      if(!wk.light) b.classList.add("lightless");
      if(i === view) b.classList.add("today");
      b.innerHTML = `<span class="n">${i+1}</span>`;
      b.setAttribute("aria-label", `Day ${i+1}: ${DAYS[i].t}${done.has(i)?" (complete)":""}`);
      b.addEventListener("click", ()=>{ view = i; renderSession(); renderGrid(); });
      row.appendChild(b);
    }
    host.appendChild(row);
  });
  const n = done.size;
  $("tally").innerHTML = `<b>${n}</b> of 42 sessions · week ${Math.min(6,Math.floor(firstUndone()/7)+1)}`;
}

/* ---------------- case diagrams ----------------
   A last-layer plan view: the 3x3 top face with a rim of 12 side stickers,
   drawn as a 5x5 grid with the corners left empty. Front face at the bottom.
   The geometry below is shared by both renderers.                        */
const D = { cell:11, gap:2, rim:4, pad:6, size:49 };
const uxy = (r,c) => [D.pad + c*(D.cell+D.gap), D.pad + r*(D.cell+D.gap)];
/* Rim slots run clockwise from the back-left: 0-2 back, 3-5 right,
   6-8 front, 9-11 left. Returns [x, y, width, height]. */
function rimRect(i){
  const s = D.pad + (i%3)*(D.cell+D.gap), e = D.size - D.rim;
  if(i<3)  return [s, 0, D.cell, D.rim];
  if(i<6)  return [e, D.pad + (i-3)*(D.cell+D.gap), D.rim, D.cell];
  if(i<9)  return [D.pad + (8-i)*(D.cell+D.gap), e, D.cell, D.rim];
  return [0, D.pad + (11-i)*(D.cell+D.gap), D.rim, D.cell];
}
const COLOUR = {B:"var(--b)",R:"var(--r)",G:"var(--g)",O:"var(--o)",Y:"var(--y)",W:"var(--w)"};
/* Custom properties resolve inside SVG presentation attributes, so the
   diagrams re-theme themselves with the rest of the page. */
const DULL = "var(--facelet-off)", DIM = "var(--facelet-dim)";
const svgOpen = `<svg viewBox="0 0 ${D.size} ${D.size}" role="img" focusable="false">`;
const rect = (x,y,w,h,fill,rx) =>
  `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx||1.5}" fill="${fill}"/>`;

/* OLL: `enc` is 21 chars — 3 back-rim, then (L,u0,u1,u2,R) per row, then 3
   front-rim. For the edge-orientation cases the corners are arbitrary, so we
   draw them dimmed rather than asserting a state that doesn't hold. */
function renderOLL(enc, edgesOnly){
  const u=[], rim=[];
  for(let r=0;r<3;r++){
    rim[r===0?11:(r===1?10:9)] = enc[3+r*5];
    for(let c=0;c<3;c++) u[r*3+c] = enc[4+r*5+c];
    rim[3+r] = enc[7+r*5];
  }
  for(let i=0;i<3;i++){ rim[i]=enc[i]; rim[8-i]=enc[18+i]; }
  const isCorner = i => i%2===0;                       // u-face corner indices 0,2,6,8
  const rimCorner = i => i%3!==1;                      // rim slots that touch a corner
  let out = svgOpen;
  for(let i=0;i<9;i++){
    if(i===4){ out += rect(...uxy(1,1), D.cell, D.cell, COLOUR.Y); continue; }  // centre is always yellow
    const arbitrary = edgesOnly && isCorner(i);
    out += rect(...uxy(Math.floor(i/3), i%3), D.cell, D.cell,
                arbitrary ? DIM : (u[i]==="1" ? COLOUR.Y : DULL));
  }
  for(let i=0;i<12;i++){
    const arbitrary = edgesOnly && rimCorner(i);
    const [x,y,w,h] = rimRect(i);
    out += rect(x,y,w,h, arbitrary ? DIM : (rim[i]==="1" ? COLOUR.Y : DULL), 1);
  }
  return out + "</svg>";
}

/* PLL: top face is fully yellow by this stage, so the rim carries the
   recognition and the arrows carry what the algorithm does. */
function renderPLL(ring, moves){
  let out = svgOpen;
  for(let r=0;r<3;r++) for(let c=0;c<3;c++)
    out += rect(...uxy(r,c), D.cell, D.cell, COLOUR.Y);   // fully oriented by this stage
  for(let i=0;i<12;i++){
    const [x,y,w,h] = rimRect(i);
    out += rect(x,y,w,h, COLOUR[ring[i]] || DULL, 1);
  }
  const centre = i => { const [x,y] = uxy(Math.floor(i/3), i%3);
                        return [x + D.cell/2, y + D.cell/2]; };
  const all = moves || [];
  const has = (a,b) => all.some(m => m[0]===a && m[1]===b);
  const head = (x,y,ux,uy) =>
    `<polygon points="${x.toFixed(1)},${y.toFixed(1)} ${(x-ux*3.4-uy*2.1).toFixed(1)},${(y-uy*3.4+ux*2.1).toFixed(1)} ${(x-ux*3.4+uy*2.1).toFixed(1)},${(y-uy*3.4-ux*2.1).toFixed(1)}" fill="var(--arrow)"/>`;
  const drawn = new Set();
  all.forEach(([a,b])=>{
    const swap = has(b,a);
    if(swap && drawn.has(b+"-"+a)) return;             // a mutual swap is one line
    drawn.add(a+"-"+b);
    const [x1,y1] = centre(a), [x2,y2] = centre(b);
    const dx = x2-x1, dy = y2-y1, len = Math.hypot(dx,dy) || 1;
    const ux = dx/len, uy = dy/len, back = 3.2;
    const sx = x1 + ux*back, sy = y1 + uy*back;
    const ex = x2 - ux*back, ey = y2 - uy*back;
    out += `<line x1="${sx.toFixed(1)}" y1="${sy.toFixed(1)}" x2="${ex.toFixed(1)}" y2="${ey.toFixed(1)}" stroke="var(--arrow)" stroke-width="1.6" stroke-linecap="round"/>`
         + head(ex,ey,ux,uy) + (swap ? head(sx,sy,-ux,-uy) : "");
  });
  return out + "</svg>";
}

let tab = "oll";
function renderAlgs(){
  const t = $("tabs"); t.innerHTML = "";
  Object.entries(ALGS).forEach(([k,v])=>{
    const b = document.createElement("button");
    b.className = "tab"; b.setAttribute("role","tab");
    b.setAttribute("aria-selected", k===tab ? "true":"false");
    b.textContent = v.label;
    b.addEventListener("click", ()=>{ tab = k; renderAlgs(); });
    t.appendChild(b);
  });

  const primer = STAGES[tab], host = $("primer");
  if(primer){
    host.innerHTML =
      `<h4>${primer.h}</h4>` + primer.p.map(x=>`<p>${x}</p>`).join("") +
      `<div class="pitfalls"><div class="k">Where it goes wrong</div><ul>` +
      primer.bad.map(x=>`<li>${x}</li>`).join("") + `</ul></div>`;
    host.style.display = "";
  } else {
    host.style.display = "none";
  }

  const l = $("alist"); l.innerHTML = "";
  ALGS[tab].rows.forEach(r=>{
    const div = document.createElement("div");
    const diagram = r.e ? renderOLL(r.e, !!r.edges) : (r.r ? renderPLL(r.r, r.x) : null);
    div.className = "arow" + (diagram ? "" : " nodiagram");
    div.innerHTML =
      (diagram ? `<div class="acase" aria-hidden="true">${diagram}</div>` : "") +
      `<div class="aname">${r.n}<small>${r.s}</small></div>` +
      `<div class="alg${tab==="f2l"?" plain":""}">${r.a}` +
        (diagram ? `<span class="setup"><b>set up</b> ${invertAlg(r.a)}</span>` : "") +
      `</div>` +
      (r.note ? `<details class="anote"><summary>What it does</summary><p>${r.note}</p></details>` : "");
    l.appendChild(div);
  });
  l.style.display = ALGS[tab].rows.length ? "" : "none";
}

function renderReading(){
  $("reading").innerHTML =
    `<div class="k">If you want to go further</div><ul>` +
    READING.map(r=>`<li><a href="${r.u}" rel="noopener noreferrer" target="_blank">${r.t}</a> <span>— ${r.d}</span></li>`).join("") +
    `</ul>`;
}

function renderAll(){ renderProfiles(); renderSession(); renderGrid(); renderAlgs(); renderReading(); }

/* ---------------- theme ----------------
   Shares Quarto's storage key and values, so the choice made here is the choice
   the rest of the site sees, and vice versa. */
const THEME_KEY = "quarto-color-scheme";
function currentTheme(){
  return document.documentElement.getAttribute("data-theme") === "dark" ? "dark" : "light";
}
function applyTheme(mode){
  document.documentElement.setAttribute("data-theme", mode);
  Store.set(THEME_KEY, mode === "dark" ? "alternate" : "default");
  const b = $("themeToggle");
  b.textContent = mode === "dark" ? "☀" : "☾";
  b.setAttribute("aria-label", mode === "dark" ? "Switch to light" : "Switch to dark");
  b.setAttribute("title", mode === "dark" ? "Switch to light" : "Switch to dark");
}

/* ---------------- events ---------------- */
$("themeToggle").addEventListener("click", ()=>{
  applyTheme(currentTheme() === "dark" ? "light" : "dark");
});
$("mark").addEventListener("click", ()=>{
  const wasDone = done.has(view);
  if(wasDone) done.delete(view); else done.add(view);
  saveProgress();
  const idx = view;
  if(!wasDone && view < DAYS.length-1) view = firstUndone();
  renderSession(); renderGrid();
  if(!wasDone){
    const cell = $("weeks").querySelectorAll(".sticker")[idx];
    if(cell){ cell.classList.add("pop"); setTimeout(()=>cell.classList.remove("pop"), 200); }
  }
});
$("nextScramble").addEventListener("click", ()=>{
  seedOverride = ""; solveN++; renderScramble();
});
$("crossBtn").addEventListener("click", showCross);
$("seedInput").addEventListener("change", e=>{
  seedOverride = e.target.value; renderScramble();
});
$("prev").addEventListener("click", ()=>{ if(view>0){ view--; renderSession(); renderGrid(); }});
$("next").addEventListener("click", ()=>{ if(view<DAYS.length-1){ view++; renderSession(); renderGrid(); }});
$("profile").addEventListener("change", e=>{
  active = e.target.value; saveProfiles(); loadProgress(); renderAll();
});
$("addProfile").addEventListener("click", ()=>{
  const name = (prompt("Name for this solver") || "").trim();
  if(!name) return;
  if(!profiles.includes(name)) profiles.push(name);
  active = name; saveProfiles(); loadProgress(); renderAll();
});
$("reset").addEventListener("click", ()=>{
  if(!confirm(`Clear all progress for ${active}? This can't be undone.`)) return;
  done.clear(); saveProgress(); view = 0; renderSession(); renderGrid();
});
document.addEventListener("keydown", e=>{
  if(e.target.matches("input,select,textarea")) return;
  if(e.key === "ArrowLeft") $("prev").click();
  if(e.key === "ArrowRight") $("next").click();
});

/* ---------------- boot ---------------- */
applyTheme(currentTheme());
saveProfiles();
loadProgress();
renderAll();
